### 本地开发环境配置
spring:
  application:
    name: task-executor
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.143.130:3306/etl
    username: root
    password: zhanwei
  cloud:
    consul:
      host: 118.31.46.174
      port: 30085
      enabled: true
      discovery:
        health-check-path: /actuator/health
        prefer-ip-address: true
  ### 调用追踪配置
  zipkin:
    base-url: http://localhost:9410
  sleuth:
    sampler:
      percentage: 1.0

