### 生产环境配置
spring:
  application:
    name: task-executor
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.143.130:3306/zuul-server
    username: root
    password: zhanwei
  cloud:
    consul:
      host: 172.16.175.222
      port: 30085
      enabled: true
      discovery:
        health-check-path: /actuator/health
        prefer-ip-address: true

cassandra:
  host: 121.42.143.130
  port: 9042
  keyspace: gateway